### PR TITLE
Add support for timestamps as DEFAULT constraints

### PR DESCRIPTION
**Pull request by otoolep**

### CODE REVIEW

**Comment by otoolep** [comment]
Part of the fix for https://github.com/rqlite/rqlite/issues/1072

**Comment by benbjohnson** [comment]
@otoolep Would you be interested in just taking over the repo? I can transfer it to your username.

**Comment by otoolep** [comment]
@benbjohnson -- sure I plan to continue work on this, for the purposes of rqlite support.

**Comment by benbjohnson** [comment]
@otoolep Sorry for the delay. It looks like you need to delete your repo first and then I can transfer it.

**Comment by otoolep** [comment]
@benbjohnson -- I moved is repo out of the way (renamed to sql-2). Want to try again?

**Comment by benbjohnson** [comment]
@otoolep I'm getting this error now: 

> "rqlite already has a repository in the benbjohnson/sql network and You don’t have the permission to create public repositories on rqlite"

It might be easier if I just delete my repo? :)

Otherwise you'll need to delete your `sql-2` repo and temporarily add me as an owner/collaborator on the `rqlite` repo.

**Pull request merged**
